# Generated by Django 4.2.3 on 2023-07-27 20:12

from django.db import migrations, models
import django.db.models.deletion
import elevator_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stations_count", models.PositiveIntegerField()),
                ("curr_station", models.PositiveIntegerField(blank=True, default=1)),
                (
                    "curr_direction",
                    models.CharField(
                        choices=[("UP", "UP"), ("DOWN", "DOWN")],
                        default=elevator_app.models.Directions["UP"],
                        max_length=50,
                    ),
                ),
                (
                    "building_name",
                    models.CharField(default="Name Unkown", max_length=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("station_no", models.PositiveIntegerField()),
                (
                    "to_station",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "served_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("skip_count", models.PositiveIntegerField(default=0)),
                (
                    "elevator_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator_app.elevatorsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
