# Generated by Django 4.2.3 on 2023-07-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elevator_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevatorrequest",
            name="station_no",
        ),
        migrations.CreateModel(
            name="ElevatorStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.PositiveIntegerField()),
                (
                    "under_maintenance_since",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "elevator_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator_app.elevatorsystem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="elevatorrequest",
            name="from_station",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_station",
                to="elevator_app.elevatorstation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="to_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_station",
                to="elevator_app.elevatorstation",
            ),
        ),
        migrations.AlterField(
            model_name="elevatorsystem",
            name="curr_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elevator_app.elevatorstation",
            ),
        ),
    ]
