# Generated by Django 4.2.3 on 2023-07-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "elevator_app",
            "0002_remove_elevatorrequest_station_no_elevatorstation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorsystem",
            name="curr_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elevator_app.elevatorstation",
            ),
        ),
    ]
