# Generated by Django 4.2.3 on 2023-07-27 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elevator_app", "0004_elevatorstation_created_elevatorstation_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevatorstation",
            old_name="floor_number",
            new_name="floor_no",
        ),
    ]
