# Generated by Django 4.2.3 on 2023-07-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elevator_app", "0005_rename_floor_number_elevatorstation_floor_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorsystem",
            name="curr_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="elevator_app.elevatorstation",
            ),
        ),
    ]
