# Generated by Django 4.2.3 on 2023-07-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elevator_app", "0006_alter_elevatorsystem_curr_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorrequest",
            name="to_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_station",
                to="elevator_app.elevatorstation",
            ),
        ),
    ]
